theme: just-the-docs
title: Algorithm 11 (A11)
description: Open standard for deterministic reasoning
logo: a11-diagram.svg

nav_order: 1

# Navigation structure
nav:
  - title: Overview
    url: a11_overview.html
  - title: Key Concepts
    url: a11_key_concepts.html
  - title: AI Developers
    url: a11_for_ai_developers.html
  - title: Autonomous Systems
    url: a11_for_autonomous_systems_developers.html
  - title: Versions
    url: versions.html
